version: '3.5'

services: 
  set-user:
    container_name: set-user
    build: ./usuario/set-user
    ports: 
      - '3000:3000'
    environment: 
      - PORT=3000
    networks:
      app_net:
        ipv4_address: 172.16.1.10 
        
  
  get-user:
    container_name: get-user
    build: ./usuario/get-user
    ports: 
      - '3002:3002'
    environment: 
      - PORT=3002
    networks:
      app_net:
        ipv4_address: 172.16.1.11 
        
  update-user:
    container_name: update-user
    build: ./usuario/update-user
    ports: 
      - '3001:3001'
    environment: 
      - PORT=3001
    networks:
      app_net:
        ipv4_address: 172.16.1.12
  
  guest-service:
    container_name: guest-service
    image: 201503470/guest-microservice:latest
    ports: 
      - '80:3005'
    networks:
      app_net:
        ipv4_address: 172.16.1.14
  
  lodging-service:
    container_name: lodging-service
    image: di3gini/lodging-microservice:latest
    ports: 
      - '4000:4000'
    networks:
      app_net:
        ipv4_address: 172.16.1.15

  frontend:
    container_name: airbnb
    build: ./Frontend/AirBnB
    ports: 
      - '80:80'
    networks:
      app_net:
        ipv4_address: 172.16.1.13



networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
    
